- become: true
  hosts: all
  name: Common tasks FTW
  pre_tasks:
  - {hostname: 'name={{inventory_hostname}}', name: Set hostname}
- become: true
  hosts: base
  name: Counter-panda service
  roles:
  - {role: python, tags: python}
  - {role: counter-panda, tags: counter-panda}
- become: true
  hosts: base
  name: Gify-panda service
  roles:
  - {role: python, tags: python}
  - {role: gify-panda, tags: gify-panda}
